[project]
name = "sqlmodel-learning-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "faker>=36.1.1",
    "sqlmodel>=0.0.23",
]
